apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - nb-cpu-wo-storage.yaml
  # - nb-cpu-w-storage.yaml
  # - nb-gpu-wo-storage.yaml
  # - nb-gpu-w-storage.yaml
