apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - hw-profiles-small.yaml

  - nb-cpu-pvc.yaml
  - nb-cpu-wo-storage.yaml
  - nb-cpu-w-storage.yaml

  - nb-gpu-pvc.yaml
  - nb-gpu-wo-storage.yaml
  # - nb-gpu-w-storage.yaml
