apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - rhoai-enable-features

resources:
  - rhoai-cluster-settings
  - rhoai-configure-logging
  - rhoai-gpu-dashboard
  - rhoai-gpu-timeslicing
  - rhoai-groups
  - rhoai-hw-profiles
  - rhoai-rbac
  - rhoai-resource-quota
  - rhoai-vllm-monitoring
