apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - operators/serverless-operator
  - operators/servicemeshoperator
  - operators/web-terminal

resources:
  # - operators/cincinnati-operator/operator/overlays/v1
  # - nvidia - TODO
  - operators/nvidia-gpu-operator
  - operators/nfd/operator/overlays/stable
  - operators/rhods-operator/instance/overlays/all
  - operators/rhods-operator/operator/overlays/stable-2.22

# patches:
#   - target:
#       kind: Subscription
#       name: web-terminal
#     patch: |-
#       - op: replace
#         path: /spec/source
#         value: cs-redhat-operator-index-v4-18
#   - target:
#       kind: Subscription
#       name: serverless-operator
#     patch: |-
#       - op: replace
#         path: /spec/source
#         value: cs-rhoai-redhat-operator-index-v4-18
#   - target:
#       kind: Subscription
#       name: servicemeshoperator
#     patch: |-
#       - op: replace
#         path: /spec/source
#         value: cs-rhoai-redhat-operator-index-v4-18
#   - target:
#       kind: Subscription
#       name: rhods-operator
#     patch: |-
#       - op: replace
#         path: /spec/source
#         value: cs-rhoai-redhat-operator-index-v4-18
